[project]
name = "Biometric-Key"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []
[contracts.biometric-key]
path = "contracts/biometric-key.clar"
clarity_version = 4
epoch = "3.3"
[repl]
costs_version = 2
parser_version = 2
[repl.analysis]
passes = ["check_checker"]